const TARGET_PER_CATEGORY = 16;

function sentence(before, blank, after) {
  return { parts: [{ text: before }, { blank }, { text: after }] };
}

function multi(...args) {
  // Alternating: text, blank, text, blank, ..., text
  return { parts: args.map((a, i) => (i % 2 === 0 ? { text: a } : { blank: a })) };
}

export const SENTENCE_BANK = {
  M: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("Lesní m", "y", "š se schovala do nory."),
        sentence("M", "y", " jsme dnes psali diktát."),
        sentence("Přem", "ý", "šlel nad úlohou celý večer."),
        sentence("Na louce bzučel hm", "y", "z."),
        sentence("Hlem", "ý", "žď lezl pomalu přes chodník."),
        sentence("Maminka šla m", "ý", "t nádobí po obědě."),
        sentence("Kluk šel zam", "y", "kat kolo do stojanu."),
        sentence("Lesníci začali m", "ý", "tit staré křoví."),
        sentence("Tatínek se m", "ý", "lil ve výpočtu."),
        sentence("V sešitě byla napsaná hlavní m", "y", "šlenka příběhu."),
        sentence("Za oknem poletoval drobný hm", "y", "z."),
        sentence("Děda vytáhl starou m", "y", "šičku ze skříně."),
        sentence("V pohádce běžela polní m", "y", "š mezi klasy."),
        sentence("Při úklidu jsme museli zam", "y", "kat sklep."),
        sentence("Před spaním jsem ještě přem", "ý", "šlel o zítřku."),
        sentence("Na jaře se na louce objevil drobný hm", "y", "z."),
      ],
      relatedWords: [
        sentence("Vítr rozfoukal jemné chm", "ý", "ří z pampelišky."),
        sentence("Kovář dm", "ý", "chal oheň v peci."),
        sentence("Nemá se sm", "ý", "kat taška po zemi."),
        sentence("Na nástěnce visí naše třídní m", "y", "šlenková mapa."),
        sentence("Učitelka ocenila moji přem", "ý", "šlivost."),
        sentence("Po větru se nad polem chvíli drželo bílé chm", "ý", "ří."),
        sentence("Kolo musíme po jízdě zam", "y", "kat řetězem."),
        sentence("Když se spletl, hned uznal svůj om", "y", "l."),
        sentence("Na stole ležela kniha o m", "y", "tologii."),
        sentence("Mlynář znal staré m", "ý", "ty o vodnících."),
        sentence("Jeho nápad byl velmi prom", "y", "šlený."),
        sentence("V dílně bylo slyšet hlasité dm", "ý", "chání měchu."),
        sentence("Správce nechal zam", "y", "kat hlavní bránu."),
        sentence("Po chybě následovala krátká oml", "y", "va."),
        sentence("Na obraze byl vidět m", "ý", "tický drak."),
        sentence("V sešitě mám zapsané hlavní m", "y", "šlenky z četby."),
      ],
      easySentences: [
        sentence("Kočka honila malou m", "y", "š pod stolem."),
        sentence("Na tabuli jsme psali slovo m", "y", "."),
        sentence("Dnes budu m", "ý", "t auto s tátou."),
        sentence("V trávě se ozval tichý hm", "y", "z."),
        sentence("Večer jsem dlouho přem", "ý", "šlel."),
        sentence("Děda se trochu zm", "ý", "lil."),
        sentence("Před odchodem musím zam", "y", "kat dveře."),
        sentence("Hlem", "ý", "žď nesl svůj domeček."),
        sentence("Vítr zvedl lehké chm", "ý", "ří."),
        sentence("Kovář dm", "ý", "chal do ohně."),
        sentence("Nechci si sm", "ý", "kat bundu po zemi."),
        sentence("Na louce létal hm", "y", "z."),
        sentence("Myška se schovala do díry a byla tam m", "y", "š."),
        sentence("Při počítání jsem se zm", "ý", "lil jen jednou."),
        sentence("Před spaním ještě chvíli přem", "ý", "šlím."),
        sentence("Maminka bude večer m", "ý", "t okna."),
      ],
      mediumSentences: [
        sentence("Když se rozpršelo, museli jsme rychle zam", "y", "kat kolárnu."),
        sentence("Při řešení hádanky jsem dlouho přem", "ý", "šlel nad správnou odpovědí."),
        sentence("Na zahradě poletoval drobný hm", "y", "z kolem květin."),
        sentence("Po chybě v sešitě jsem uznal, že jsem se zm", "ý", "lil."),
        sentence("Kovář trpělivě dm", "ý", "chal, aby se železo rozžhavilo."),
        sentence("V koutě sklepa se objevila malá m", "y", "š a hned utekla."),
        sentence("Po úklidu jsme nezapomněli zam", "y", "kat zadní branku."),
        sentence("Na jaře vítr snadno rozfouká chm", "ý", "ří z pampelišek."),
        sentence("Když se soustředím, dokážu lépe přem", "ý", "šlet o úloze."),
        sentence("Babička se jen usmála, když zjistila, že se děda zm", "ý", "lil."),
        sentence("Na cestě lezl hlem", "ý", "žď, proto jsme ho opatrně obešli."),
        sentence("Po dešti zůstalo na louce mnoho hm", "y", "zu u kaluží."),
        sentence("Děti se učily, že se batoh nemá sm", "ý", "kat po zemi."),
        sentence("V dílně se ozývalo pravidelné dm", "ý", "chání velkého měchu."),
        sentence("Před odjezdem musel správce ještě zam", "y", "kat sklad."),
        sentence("Při čtení příběhu jsem si zapisoval hlavní m", "y", "šlenky."),
      ],
      trickQuestions: [
        sentence("Na stole stála velká m", "í", "sa s čerstvým ovocem."),
        sentence("Sedni si na volné m", "í", "sto u okna."),
        sentence("M", "í", "č přelétnul přes plot na sousedovu zahradu."),
        sentence("Po válce lidé toužili po trvalém m", "í", "ru."),
        sentence("M", "i", "str Kopecký opravil naše staré hodiny."),
        sentence("Napsal babičce m", "i", "lý vánoční dopis."),
        sentence("V kapse jsem našel jen jednu starou m", "i", "nci."),
        sentence("Za m", "i", "nutu zazvoní a půjdeme na přestávku."),
        sentence("Závodník m", "i", "nul cíl jako první v celém závodě."),
        sentence("Dnes bylo m", "í", "rné počasí bez deště a větru."),
        multi("M", "i", "str přem", "ý", "šlel, jak nejlépe opravit rozbité hodiny."),
        multi("Na m", "í", "stě v hluboké m", "ý", "tině žili drobní brouci."),
        multi("M", "i", "lý dopis byl plný m", "y", "šlenek na rozloučenou."),
        multi("Kolem m", "í", "sy poletoval drobný hm", "y", "z."),
        multi("Závodník m", "i", "nul branku a zm", "ý", "lil se ve směru."),
        multi("Pod starou m", "í", "sou bylo ukryto m", "y", "ší hnízdo."),
      ],
    },
  },
  P: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("Dostal p", "y", "tel plný bonbónů."),
        sentence("Netop", "ý", "r létá v noci."),
        sentence("Ryba otevřela p", "y", "sk a chytila mušku."),
        sentence("Jeho p", "ý", "cha ho přišla draho."),
        sentence("Na jaře se ve vzduchu šíří p", "y", "l z květů."),
        sentence("Kůň si zvedl ko", "py", "to."),
        sentence("Turista nesl těžký p", "y", "tel na zádech."),
        sentence("Po pádu si odřel horní p", "y", "sk."),
        sentence("Nebuď tak p", "ý", "šný před ostatními."),
        sentence("Včely nosí do úlu žlutý p", "y", "l."),
        sentence("V sáčku byl nový p", "y", "tel na cvičky."),
        sentence("Večer se u půdy objevil netop", "ý", "r."),
        sentence("Kapr rychle zavřel p", "y", "sk."),
        sentence("Po louce se nesl jemný p", "y", "l."),
        sentence("Kůň se odrazil silným ko", "py", "tem."),
        sentence("Na stupních vítězů nestál žádný p", "ý", "šný chlapec."),
      ],
      relatedWords: [
        sentence("Jeho p", "ý", "cha byla všem nepříjemná."),
        sentence("Při běhu začal klop", "ý", "tat o kameny."),
        sentence("Na květech byl vidět jemný p", "y", "l."),
        sentence("Na výlet jsem si přibalil malý p", "y", "tlík se svačinou."),
        sentence("Kůň zanechal na cestě hluboké ko", "py", "tní stopy."),
        sentence("V řece plaval kapří p", "y", "sek mezi kameny."),
        sentence("Nadutá p", "ý", "cha člověka často oslepí."),
        sentence("Ve sklepě se skrýval netop", "ý", "r."),
        sentence("Na trávníku byla vidět vrstva p", "y", "lu z borovic."),
        sentence("Na stole ležel malý p", "y", "tlík se svačinou."),
        sentence("Když zakopl, ozvalo se hlasité klop", "ý", "tnutí boty."),
        sentence("Učitel vysvětloval, jak se šíří p", "y", "l z květů."),
        sentence("Na dvoře ležela ko", "py", "ta sena u zdi."),
        sentence("Malý p", "y", "tlíček se snadno vešel do kapsy."),
        sentence("Rybář čekal, až kapr znovu otevře p", "y", "sk."),
        sentence("Předvádět svou p", "ý", "chu se nevyplácí."),
      ],
      easySentences: [
        sentence("Mám nový p", "y", "tel na tělocvik."),
        sentence("Na půdě visel netop", "ý", "r."),
        sentence("Ryba otevřela p", "y", "sk."),
        sentence("Na květech ležel p", "y", "l."),
        sentence("Kůň udělal vysoký ko", "py", "t."),
        sentence("Nebudu p", "ý", "šný."),
        sentence("Po běhu jsem trochu klop", "ý", "tal."),
        sentence("Pytel byl plný brambor a byl to těžký p", "y", "tel."),
        sentence("Na tváři měl škrábanec na p", "y", "sku."),
        sentence("Na jaře často létá p", "y", "l."),
        sentence("Večer jsme viděli netop", "ý", "ra nad střechou."),
        sentence("Před školou ležel malý p", "y", "tlík s kaštany."),
        sentence("Ryba rychle zavřela p", "y", "sk."),
        sentence("Na cestě se zvedla ko", "py", "ta hlíny."),
        sentence("Kdo se chlubí, bývá p", "ý", "šný."),
        sentence("Včela sbírá p", "y", "l z květů."),
      ],
      mediumSentences: [
        sentence("Turista si hodil p", "y", "tel na záda a vyrazil do kopce."),
        sentence("Za soumraku jsme na půdě zahlédli tichého netop", "ý", "ra."),
        sentence("Kapr se vynořil a na chvíli otevřel p", "y", "sk nad hladinou."),
        sentence("Na parapetu zůstala po jaru žlutá vrstva p", "y", "lu."),
        sentence("Při skoku přes kaluž kůň prudce zvedl ko", "py", "ta."),
        sentence("Když se chlubí, působí zbytečně p", "ý", "šně."),
        sentence("Po kamenité cestě jsme začali lehce klop", "ý", "tat o kořeny."),
        sentence("Na rameni nesl těžký p", "y", "tel se dřevem."),
        sentence("Po pádu z kola si odřel p", "y", "sk i koleno."),
        sentence("Učitel vysvětloval, jak vypadá květový p", "y", "l pod mikroskopem."),
        sentence("Ve stodole visel starý p", "y", "tel na obilí."),
        sentence("Nad řekou kroužil netop", "ý", "r a lovil hmyz."),
        sentence("Kapr otevřel p", "y", "sk, když čekal na krmení."),
        sentence("Na cestě zůstaly hluboké otisky ko", "py", "t koně."),
        sentence("Nechtěl působit p", "ý", "šně, proto mlčel."),
        sentence("Ve třídě jsme mluvili o tom, odkud se bere jarní p", "y", "l."),
      ],
      trickQuestions: [
        sentence("Rád p", "i", "ji vodu z kohoutku."),
        sentence("Zazpívali jsme krásnou vánoční p", "í", "seň."),
        sentence("Rozhodčí zapískal na p", "í", "šťalku."),
        sentence("P", "i", "lný žák se vždy naučí nové věci."),
        sentence("P", "i", "lot bezpečně přistál na letišti."),
        sentence("Na hodině jsme procvičovali velká p", "í", "smena."),
        sentence("O víkendu jsme šli na p", "i", "knik do lesa."),
        sentence("Na záhonu u plotu kvetly růžové p", "i", "voňky."),
        sentence("Truhlář vzal ze stolu těžkou p", "i", "lu."),
        sentence("Úspěch přišel díky vytrvalosti a p", "í", "li."),
        multi("P", "i", "lný žák nesl těžký p", "y", "tel knih domů."),
        multi("P", "í", "seň o netop", "ý", "rovi se dětem velmi líbila."),
        multi("P", "i", "lot si vzal zásoby v malém p", "y", "tlíku."),
        multi("P", "i", "knik p", "ý", "šně dopadl, ale nikdo se nezlobil."),
        multi("Při p", "í", "li pracoval hrnčíř a tvaroval velký ko", "py", "to."),
        multi("P", "i", "voňka rostla u stáje, kde stálo staré ko", "py", "to."),
      ],
    },
  },
  L: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("Děti vzaly l", "y", "že a šly na svah."),
        sentence("Bolelo mě l", "ý", "tko po běhu."),
        sentence("Dědeček byl na hlavě l", "y", "sý."),
        sentence("Jelen měl krásné pal", "y", "hy."),
        sentence("Naučil se hrát na l", "y", "ru."),
        sentence("Na louce voněl pel", "y", "něk."),
        sentence("Potok byl po létě velmi pl", "y", "tký."),
        sentence("Večer se začalo bl", "ý", "skat."),
        sentence("Když jím rychle, musím víc pol", "y", "kat."),
        sentence("Čas nám při výletě rychle pl", "y", "nul."),
        sentence("Nemáme pl", "ý", "tvat vodou."),
        sentence("Ze smutku začal vzl", "y", "kat."),
        sentence("Na horách jsme nazuli l", "y", "že."),
        sentence("Po běhu mě píchalo v l", "ý", "tku."),
        sentence("Starý pán byl skoro celý l", "y", "sý."),
        sentence("V sále zněla tichá l", "y", "ra."),
      ],
      relatedWords: [
        sentence("Na louce rostl pel", "y", "ňkový keřík u cesty."),
        sentence("Po dešti zůstal potok jen mělce pl", "y", "tký."),
        sentence("Ve zprávách hlásili silné bl", "ý", "skání nad městem."),
        sentence("Při obědě se nesmí hltat a rychle pol", "y", "kat."),
        sentence("Odpoledne nám výlet rychle upl", "y", "nul."),
        sentence("Ve škole jsme mluvili o pl", "y", "tvání vodou."),
        sentence("Malý chlapec ze smutku popotahoval a vzl", "y", "kal."),
        sentence("Ve sněhu byly vidět dlouhé l", "y", "žařské stopy."),
        sentence("Po tréninku mě bolel l", "ý", "tkový sval."),
        sentence("Lesník našel v trávě shoz jeleních pal", "y", "h."),
        sentence("Hudebník pečlivě ladil struny své l", "y", "ry."),
        sentence("Na poli se rozšířil pel", "y", "ňkový pach."),
        sentence("Kámen spadl do pl", "y", "tké vody u břehu."),
        sentence("Za bouřky bylo slyšet časté bl", "ý", "skání."),
        sentence("Při kašli člověk těžko pol", "y", "ká."),
        sentence("Od rána den rychle upl", "y", "nul."),
      ],
      easySentences: [
        sentence("V zimě jedeme na l", "y", "žích."),
        sentence("Po běhu mě bolí l", "ý", "tko."),
        sentence("Děda je trochu l", "y", "sý."),
        sentence("Jelen má velké pal", "y", "hy."),
        sentence("Sestra hraje na l", "y", "ru."),
        sentence("Na louce roste pel", "y", "něk."),
        sentence("Voda je dnes pl", "y", "tká."),
        sentence("Na nebi se začalo bl", "ý", "skat."),
        sentence("Musím dobře pol", "y", "kat."),
        sentence("Čas rychle pl", "y", "ne."),
        sentence("Nemáme pl", "ý", "tvat jídlem."),
        sentence("Malé dítě začalo vzl", "y", "kat."),
        sentence("Na kopci máme rádi l", "y", "žování."),
        sentence("Po skoku mě zabolelo l", "ý", "tko."),
        sentence("Starý strom byl skoro l", "y", "sý bez listí."),
        sentence("Na koncertě zazněla l", "y", "ra."),
      ],
      mediumSentences: [
        sentence("Na horách jsme si brzy ráno připnuli l", "y", "že a sjeli první svah."),
        sentence("Po dlouhém běhu do schodů mě nepříjemně bolelo pravé l", "ý", "tko."),
        sentence("Dědeček se smál, že je nahoře už úplně l", "y", "sý."),
        sentence("Mladý jelen se prodíral lesem a jeho pal", "y", "hy se zachytily o větev."),
        sentence("Hudebnice zahrála tichou melodii na starou l", "y", "ru."),
        sentence("Na kraji pole jsme ucítili výraznou vůni pel", "y", "ňku."),
        sentence("Po suchém létě zůstal potok nezvykle pl", "y", "tký."),
        sentence("Večer jsme z okna pozorovali vzdálené bl", "ý", "skání."),
        sentence("Když jíš příliš rychle, musíš zbytečně pol", "y", "kat."),
        sentence("Celé odpoledne nám při hrách venku rychle upl", "y", "nulo."),
        sentence("Paní učitelka připomněla, že se nemá pl", "ý", "tvat chlebem."),
        sentence("Malý bratr se lekl tmy a začal tiše vzl", "y", "kat."),
        sentence("Při výuce jsme zkoušeli, jak správně zabrzdit na l", "y", "žích."),
        sentence("Po túře jsem cítil únavu hlavně v l", "ý", "tkách."),
        sentence("Na stráni jsme zahlédli jelena s mohutnými pal", "y", "hami."),
        sentence("Při bouřce se nejdřív zablesklo a pak se začalo bl", "ý", "skat."),
      ],
      trickQuestions: [
        sentence("L", "í", "ný žák nenosil domácí úkoly."),
        sentence("Nové město se mi tam moc l", "í", "bilo."),
        sentence("Ze starého stromu spadl žlutý l", "i", "st."),
        sentence("Pod starou l", "í", "pou stál dřevěný stůl."),
        sentence("L", "i", "ška se plížila ke kurníku."),
        sentence("Babička pohladila vnuka po l", "í", "čku."),
        sentence("Ztratil jsem l", "í", "stek na autobus."),
        sentence("L", "i", "monádu jsme si koupili u stánku."),
        sentence("Jarní l", "i", "stí bylo jasně zelené."),
        sentence("Vrátil se s l", "í", "tostí, že přišel pozdě."),
        multi("L", "i", "ška ukradla l", "y", "ru ze zahradního domečku."),
        multi("Pod l", "í", "pou zůstaly l", "y", "že přes celou zimu."),
        multi("L", "í", "ný chlapec si nechával l", "ý", "tka neprohnutá."),
        multi("L", "i", "ška má l", "ý", "tka tak štíhlá, že téměř nezanechá stopu."),
        multi("Na l", "i", "stu byl nakreslen obrázek l", "y", "žaře."),
        multi("S l", "í", "tostí zavřel l", "y", "žárnu a odešel domů."),
      ],
    },
  },
  B: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("Budeme b", "y", "dlet u babičky na prázdninách."),
        sentence("Bydlíme v malém b", "y", "tě na kraji města."),
        sentence("Louku pokryla zelená b", "y", "lina."),
        sentence("Farmář vedl na pastvu mladého b", "ý", "ka."),
        sentence("Ko", "by", "la se pásla na louce."),
        sentence("To je u nás ob", "y", "čej."),
        sentence("B", "y", "strý žák vyřešil úkol rychle."),
        sentence("Na kraji lesa rostla bab", "y", "ka."),
        sentence("B", "y", "l jsem doma sám."),
        sentence("Musíme b", "ý", "t potichu v knihovně."),
        sentence("Ve městě přibyl nový ob", "y", "vatel."),
        sentence("Na stole ležel plán našeho b", "y", "tu."),
        sentence("Tatínek chce b", "y", "dlit blíž škole."),
        sentence("Na poli stál silný b", "ý", "k."),
        sentence("Každá zahrada má svoji b", "y", "linu."),
        sentence("Je to starý ob", "y", "čej v naší rodině."),
      ],
      relatedWords: [
        sentence("Po stěhování jsme si zvykali na nové b", "y", "dlení."),
        sentence("Ve třídě jsme mluvili o lesních b", "y", "linách."),
        sentence("Ze stáje se ozvalo hlasité bučení b", "ý", "ka."),
        sentence("Na louce běželo kob", "y", "lčí hříbě za matkou."),
        sentence("Babička zná mnoho starých ob", "y", "čejů."),
        sentence("Paní učitelka říkala, že mám b", "y", "strou hlavu."),
        sentence("V paneláku je hodně ob", "y", "vatel."),
        sentence("Domů jsme vybírali nový náb", "y", "tek."),
        sentence("Naše b", "y", "dlení je klidné."),
        sentence("Na louce rostly léčivé b", "y", "linky u plotu."),
        sentence("Mladý b", "ý", "ček běžel za stádem."),
        sentence("V ohradě se pásla mladá kob", "y", "lka."),
        sentence("Dodržování ob", "y", "čejů nás učí úctě."),
        sentence("Její b", "y", "strost byla znát při soutěži."),
        sentence("Nový ob", "y", "vatel se hned seznámil se sousedy."),
        sentence("V pokoji přibylo nové křeslo z náb", "y", "tku."),
      ],
      easySentences: [
        sentence("Chceme spolu b", "y", "dlet."),
        sentence("Bydlíme v malém b", "y", "tě."),
        sentence("Na louce roste b", "y", "lina."),
        sentence("Za plotem stál b", "ý", "k."),
        sentence("Na pastvě byla kob", "y", "la."),
        sentence("To je náš ob", "y", "čej."),
        sentence("Petr je velmi b", "y", "strý."),
        sentence("Dnes b", "y", "du doma a budu číst."),
        sentence("Já jsem tam b", "y", "l včera."),
        sentence("Musím tam b", "ý", "t včas."),
        sentence("Do domu se nastěhoval nový ob", "y", "vatel."),
        sentence("V pokoji máme starý náb", "y", "tek."),
        sentence("Naše rodina chce lépe b", "y", "dlet."),
        sentence("Zahrádku zdobí zelené b", "y", "liny."),
        sentence("Na poli se pásl b", "ý", "k."),
        sentence("Kob", "y", "la běžela k ohradě."),
      ],
      mediumSentences: [
        sentence("Po prázdninách budeme chvíli b", "y", "dlet u dědečka na chalupě."),
        sentence("V novém b", "y", "tě jsme si hned zařídili dětský pokoj."),
        sentence("Na kraji cesty rostla voňavá b", "y", "lina mezi kameny."),
        sentence("Farmář opatrně vedl rozlobeného b", "ý", "ka do stáje."),
        sentence("Za ohradou se klidně pásla hnědá kob", "y", "la."),
        sentence("U nás doma je ob", "y", "čej péct vánočku už v pátek."),
        sentence("B", "y", "strý chlapec rychle pochopil zadání úlohy."),
        sentence("Do vesnice se přistěhoval nový ob", "y", "vatel z města."),
        sentence("Rodiče vybírali do kuchyně světlý náb", "y", "tek."),
        sentence("Po škole jsem b", "y", "l chvíli venku s kamarády."),
        sentence("Na návštěvě musíme b", "ý", "t slušní a potichu."),
        sentence("Naše rodina chce příští rok b", "y", "dlet blíž práci."),
        sentence("Do sešitu jsme lepili sušenou b", "y", "linu."),
        sentence("Silný b", "ý", "k se zastavil až u napajedla."),
        sentence("Kob", "y", "la se po dešti rozběhla po pastvině."),
        sentence("Každý kraj má trochu jiný ob", "y", "čej při slavnostech."),
      ],
      trickQuestions: [
        sentence("Sníh na horách je b", "í", "lý."),
        sentence("Ve středověku se odehrála velká b", "i", "tva."),
        sentence("Pastýř měl v ruce dlouhý b", "i", "č."),
        sentence("Hodiny b", "i", "jí každou celou hodinu."),
        sentence("Na prérii žili velcí b", "i", "zoni."),
        sentence("Bratr jezdí každý den do školy na b", "i", "cyklu."),
        sentence("Ve vesnici panovala strašná b", "í", "da."),
        sentence("Do těsta přidáme b", "í", "lek z jednoho vejce."),
        sentence("B", "í", "lé zdivo vynikalo na pozadí tmavého lesa."),
        sentence("Šlechtic b", "i", "čoval koně, aby jel rychleji."),
        multi("B", "í", "lý b", "ý", "k se pásl klidně na louce."),
        multi("B", "í", "da nastala, když b", "ý", "k vyběhl z ohrady."),
        multi("B", "i", "tva b", "y", "la zdlouhavá a vyčerpávající."),
        multi("B", "í", "lá kob", "y", "la b", "y", "la nejrychlejší v závodě."),
        multi("B", "i", "č praštil a b", "ý", "k se okamžitě zastavil."),
        multi("B", "i", "cykl stál u b", "y", "liny, která voněla mátou."),
      ],
    },
  },

  F: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("Na hodině jsme probírali základy f", "y", "ziky."),
        sentence("F", "y", "zika je věda o přírodě."),
        sentence("Náš učitel f", "y", "ziky rád ukazuje pokusy."),
        sentence("F", "y", "zické cvičení je pro zdraví důležité."),
        sentence("Ve škole máme hodinu f", "y", "ziky dvakrát týdně."),
        sentence("Tatínek pracuje jako f", "y", "zioterapeut."),
        sentence("F", "y", "ziologie se zabývá funkcemi těla."),
        sentence("Na f", "y", "zikálním vyšetření mě poslouchali."),
        sentence("F", "y", "zická námaha ho pěkně unavila."),
        sentence("Na škole v přírodě jsme dělali f", "y", "zické aktivity."),
        sentence("F", "y", "zioterapeutka mi pomohla s bolestí zad."),
        sentence("Zákon f", "y", "ziky platí všude ve vesmíru."),
        sentence("F", "y", "zické zdraví je stejně důležité jako duševní."),
        sentence("Chlapec měl velký talent na f", "y", "ziku."),
        sentence("F", "y", "zikální zákon popsali vědci před staletími."),
        sentence("F", "y", "zioterapeut nás naučil správně dýchat."),
      ],
      relatedWords: [
        sentence("F", "y", "zická práce ho bavila víc než psaní."),
        sentence("Učitelka f", "y", "ziky přinesla magnet na pokus."),
        sentence("Po úrazu jsem chodil na f", "y", "zioterapii."),
        sentence("F", "y", "zikální jev byl pro nás velmi zajímavý."),
        sentence("Na f", "y", "zioterapii mi cvičení velice pomohlo."),
        sentence("F", "y", "ziologicky je člověk přizpůsoben pohybu."),
        sentence("Na hodině f", "y", "ziky jsme měřili teplotu vody."),
        sentence("F", "y", "zická zdatnost se zlepšuje pravidelným cvičením."),
        sentence("Ve f", "y", "zikálním kabinetu jsou různé přístroje."),
        sentence("F", "y", "zioterapeut mu předepsal cvičení na záda."),
        sentence("Zákon f", "y", "ziky říká, že každá akce má reakci."),
        sentence("F", "y", "zická práce na zahradě ho baví každý den."),
        sentence("F", "y", "zioterapeuti pracují v nemocnicích i v ordinacích."),
        sentence("Při hodině f", "y", "ziky jsme měřili rychlost pohybujícího se auta."),
        sentence("F", "y", "ziologicky je spánek nezbytný pro zdraví."),
        sentence("Náš f", "y", "zický trenér nás naučil správnou techniku."),
      ],
      easySentences: [
        sentence("F", "y", "zika mě baví ve škole."),
        sentence("Na f", "y", "zice jsme dělali pokus."),
        sentence("Mám rád hodinu f", "y", "ziky."),
        sentence("F", "y", "zické cvičení je zdravé."),
        sentence("Chodím na f", "y", "zioterapii."),
        sentence("F", "y", "zioterapeut mi pomáhá."),
        sentence("Na f", "y", "ziku se musím připravit."),
        sentence("F", "y", "zická práce mě baví."),
        sentence("Ve škole mám f", "y", "ziku."),
        sentence("F", "y", "zikální zákon je důležitý."),
        sentence("Tatínek je f", "y", "zioterapeut."),
        sentence("F", "y", "zika je věda."),
        sentence("Ráda chodím na f", "y", "zioterapii."),
        sentence("F", "y", "zické zdraví je důležité."),
        sentence("Na hodině f", "y", "ziky jsme počítali."),
        sentence("F", "y", "zický trénink byl dnes těžký."),
      ],
      mediumSentences: [
        sentence("Na hodině f", "y", "ziky jsme zkoumali, jak funguje magnet."),
        sentence("F", "y", "zická aktivita pomáhá udržovat dobrou náladu."),
        sentence("Po operaci chodil tatínek na f", "y", "zioterapii každý týden."),
        sentence("Zákon f", "y", "ziky, který jsme probírali, byl pro mě úplně nový."),
        sentence("F", "y", "zioterapeut nás naučil cviky na správné sezení."),
        sentence("Ve f", "y", "zikálním kabinetu visí plakát se sluneční soustavou."),
        sentence("F", "y", "ziologicky potřebuje tělo osm hodin spánku."),
        sentence("Na soustředění jsme dělali různé f", "y", "zické aktivity venku."),
        sentence("F", "y", "zikální vyšetření ukázalo, že jsem zdravý."),
        sentence("Zákon f", "y", "ziky nelze porušit, ani kdybychom chtěli."),
        sentence("F", "y", "zioterapeutka mi doporučila plavání kvůli zádům."),
        sentence("Na hodině f", "y", "ziky jsme stavěli jednoduchý elektrický obvod."),
        sentence("F", "y", "zická příprava sportovce trvá mnoho dlouhých měsíců."),
        sentence("F", "y", "ziologicky je smích velmi prospěšný pro zdraví."),
        sentence("Ve f", "y", "zikální laboratoři pracují vědci na výzkumu."),
        sentence("F", "y", "zioterapie mi pomohla vrátit se ke sportu."),
      ],
      trickQuestions: [
        sentence("V obchodě prodávají f", "i", "alové pastelky."),
        sentence("Náš táta pracuje ve velké f", "i", "rmě."),
        sentence("Koupili jsme nový f", "i", "lm pro celou rodinu."),
        sentence("Na plotě seděla f", "i", "nka a čekala na krmení."),
        sentence("V knihovně jsem si půjčil f", "i", "lozofickou knihu."),
        sentence("F", "i", "alová barva je moje oblíbená."),
        sentence("Maminka má ráda f", "i", "lm s dobrým koncem."),
        sentence("F", "i", "nancování projektu schválil ředitel."),
        sentence("Tatínek si koupil nový f", "i", "x na opravu trubky."),
        sentence("F", "i", "rmě se loni dařilo velmi dobře."),
        sentence("V muzeu visí krásné f", "i", "gurky ze starého Egypta."),
        sentence("Na závodě vyhrál náš kamarád a dostal f", "i", "nálový pohár."),
        sentence("Doma máme velkou f", "i", "kus v květináči."),
        sentence("F", "i", "gura šachového koně je nejsložitější."),
        sentence("Na svátek dostala maminka krásné f", "i", "alové tulipány."),
        sentence("F", "i", "rm v centru města je stále víc."),
      ],
    },
  },
  S: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("Její s", "y", "n chodí do druhé třídy."),
        sentence("Na chlebu máme tvrdý s", "ý", "r."),
        sentence("Maso bylo s", "y", "rové, nestálo za nic."),
        sentence("Po obědě jsem byl úplně s", "y", "tý."),
        sentence("Na větvi seděla malá s", "ý", "kora."),
        sentence("Ráno bylo s", "y", "chravo a foukal vítr."),
        sentence("Babička s", "y", "pala mouku do mísy."),
        sentence("V poli žije malý s", "y", "sel."),
        sentence("Hláska s patří mezi s", "y", "kavky."),
        sentence("Had s", "y", "kal, když se přiblížil pes."),
        sentence("Polévka nás pěkně nas", "y", "tila."),
        sentence("S", "ý", "r z Francie je velmi voňavý."),
        sentence("S", "y", "n se vrátil ze školy celý umazaný."),
        sentence("S", "y", "rové maso se nemá jíst."),
        sentence("S", "ý", "korka skákala po větvích."),
        sentence("V zimě bylo s", "y", "chravo a ošklivo."),
      ],
      relatedWords: [
        sentence("Maminka s", "y", "nkovi uvařila jeho oblíbenou polévku."),
        sentence("S", "ý", "rárna v naší vesnici dělá výborné sýry."),
        sentence("Kuchař přidal s", "y", "rovou omáčku k masu."),
        sentence("Po vydatném jídle jsem se cítil nas", "y", "cen."),
        sentence("S", "ý", "korky přilétaly k oknu pro zrnka."),
        sentence("S", "y", "chravo počasí kazí chuť na procházku."),
        sentence("Z pytlíku se s", "y", "palo koření na prkénko."),
        sentence("S", "y", "sel si udělal noru pod starým pařezem."),
        sentence("S", "y", "kavky jsou hlásky jako s, z nebo š."),
        sentence("Had s", "y", "kal varovně, než zaútočil."),
        sentence("S", "y", "nkův batoh váží skoro pět kilo."),
        sentence("S", "ý", "rový koláč byl na oslavě velmi oblíbený."),
        sentence("S", "y", "rové ryby je třeba nejdřív tepelně zpracovat."),
        sentence("Mít nas", "y", "cenou rodinu je pro kuchaře velká odměna."),
        sentence("S", "ý", "korka je jeden z nejběžnějších ptáků u nás."),
        sentence("S", "y", "chravé podzimní ráno nás příliš nepotěšilo."),
      ],
      easySentences: [
        sentence("Mám ráda s", "ý", "r na chlebu."),
        sentence("Její s", "y", "n je hodný kluk."),
        sentence("Venku bylo s", "y", "chravo."),
        sentence("Na větvi seděla s", "ý", "kora."),
        sentence("Babička s", "y", "pala cukr do těsta."),
        sentence("Po jídle jsem byl s", "y", "tý."),
        sentence("Maso bylo s", "y", "rové."),
        sentence("V poli žije s", "y", "sel."),
        sentence("Had s", "y", "kal na nás."),
        sentence("Polévka nás nas", "y", "tila."),
        sentence("S", "y", "n přišel ze školy."),
        sentence("S", "ý", "r je z mléka."),
        sentence("S", "y", "rové jídlo není dobré."),
        sentence("S", "ý", "kora zpívala v zahradě."),
        sentence("Pekař s", "y", "pal mouku do díže."),
        sentence("Ráno bylo s", "y", "chravo a chladno."),
      ],
      mediumSentences: [
        sentence("Maminka s", "y", "nkovi připravila svačinu a uložila ji do aktovky."),
        sentence("Ve s", "ý", "rárně vyrábějí různé druhy sýrů pro celý kraj."),
        sentence("S", "y", "rové maso bychom nikdy neměli podávat malým dětem."),
        sentence("Po výdatném obědě jsem se cítil pěkně nas", "y", "cen a unavený."),
        sentence("S", "ý", "kory přilétaly k ptačí budce, kde bylo nasypané zrní."),
        sentence("S", "y", "chravé říjnové ráno nás přivítalo hustou mlhou."),
        sentence("Babička opatrně s", "y", "pala mouku z pytle do velké mísy."),
        sentence("S", "y", "sel žije v norách a v zimě se neprobudí."),
        sentence("S", "y", "kavky jsou hlásky, při jejichž výslovnosti vzniká sykavý zvuk."),
        sentence("Had varovně s", "y", "kal, když jsme se přiblížili příliš blízko."),
        sentence("S", "y", "nkův přítel přišel po škole hrát fotbal na hřiště."),
        sentence("Kvalitní s", "ý", "r poznáme podle barvy, vůně i chuti."),
        sentence("S", "y", "rový pokrm z masa je oblíbený v mnoha zemích světa."),
        sentence("Polévka nás pěkně nas", "y", "tila, takže jsme druhý chod vynechali."),
        sentence("S", "ý", "kora šplhala po kmeni břízy a hledala potravu."),
        sentence("S", "y", "chravé počasí trvalo celý týden a slunce nesvítilo."),
      ],
      trickQuestions: [
        sentence("Na s", "i", "lnici byl velký provoz."),
        sentence("Přinesl jsem sklenici s", "i", "rupu z lékárny."),
        sentence("Tento kluk má velmi s", "i", "lné svaly."),
        sentence("Přišel s", "i", "ce pozdě, ale alespoň přišel."),
        sentence("Koník byl s", "i", "lný a rychlý."),
        sentence("Na s", "i", "lvestrovské oslavě bylo veselo."),
        sentence("S", "i", "lná bouřka přišla náhle a bez varování."),
        sentence("Poprosila ho s", "i", "ce tiše, ale důrazně."),
        sentence("Muž byl s", "i", "lný jako medvěd."),
        sentence("Ten balík byl s", "i", "lně těžký na zvednutí."),
        sentence("Na s", "i", "lnici svítí lampy celou noc."),
        sentence("S", "i", "lvestr slavíme poslední den v roce."),
        sentence("S", "i", "lný vítr skácel starý strom na zahradě."),
        sentence("Řekla s", "i", "ce ne, ale pak si to rozmyslela."),
        sentence("S", "i", "rup pomáhá při kašli a bolesti v krku."),
        sentence("S", "i", "lnice vedla přes les k malé vesnici."),
      ],
    },
  },
  V: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("V", "y", " jste výborný tým!"),
        sentence("Na skále seděl velký v", "ý", "r."),
        sentence("Pes začal v", "ý", "t bolestí."),
        sentence("V", "y", "žle je štíhlý lovecký pes."),
        sentence("Na stromě bylo velmi v", "y", "soké ptačí hnízdo."),
        sentence("U řeky jsme viděli v", "y", "dru."),
        sentence("Děti radostně v", "ý", "skaly, když přijel cirkus."),
        sentence("V", "y", " víte, co je správné."),
        sentence("Nočním lesem se nesl vlčí v", "ý", "t."),
        sentence("V", "ý", "r je velký noční pták."),
        sentence("V", "y", "dra je chráněný živočich."),
        sentence("V", "ý", "soká hora se tyčila nad údolím."),
        sentence("Děti v", "ý", "skaly radostí u stromečku."),
        sentence("V", "y", "žle má tenké nohy a krátkou srst."),
        sentence("Vlk v", "ý", "l celou noc pod měsícem."),
        sentence("V", "y", "dra ulovila rybu a snědla ji na břehu."),
      ],
      relatedWords: [
        sentence("Učitel nás v", "y", "zval k tabuli."),
        sentence("Správce v", "y", "hlásil nástup na hřiště."),
        sentence("Celý tým v", "y", "hrál zápas bez problémů."),
        sentence("Na prázdniny jsme v", "y", "jeli na hory."),
        sentence("Maminka v", "y", "prala všechno prádlo."),
        sentence("Děda v", "y", "právoval příběhy z mládí."),
        sentence("Učitelka v", "y", "brala nejhezčí obrázky na výstavu."),
        sentence("V", "ý", "roba mléka na farmě je každodenní práce."),
        sentence("Lekce v", "y", "šla opravdu skvěle."),
        sentence("Záchranáři v", "y", "tahovali uvízlé auto z příkopu."),
        sentence("Tatínek v", "y", "nesl odpadky ven."),
        sentence("V", "y", "pravili jsme se brzy ráno."),
        sentence("Maminka nám v", "y", "světlila, jak se správně myjí ruce."),
        sentence("V", "ý", "kop byl přesný a míč skončil v síti."),
        sentence("Děti v", "y", "bíhaly ven, jakmile zazvonil zvonek."),
        sentence("Správce v", "ý", "věsil ceduli na dveře."),
      ],
      easySentences: [
        sentence("V", "y", " jste šikovní žáci."),
        sentence("Na skále seděl v", "ý", "r."),
        sentence("Pes v", "ý", "l celou noc."),
        sentence("U řeky žije v", "y", "dra."),
        sentence("Hory jsou v", "ý", "soké."),
        sentence("Děti v", "ý", "skaly radostí."),
        sentence("V", "y", "žle je lovecký pes."),
        sentence("V", "y", " jste moji přátelé."),
        sentence("Vlk v", "ý", "l v lese."),
        sentence("V", "y", "dra plave rychle."),
        sentence("V", "ý", "r hledá v noci potravu."),
        sentence("Hlas byl v", "ý", "soký a pronikavý."),
        sentence("Děti v", "ý", "skaly u vánočního stromečku."),
        sentence("V", "y", "žle bývá dobrým lovcem."),
        sentence("Vlkodav v", "ý", "l na měsíc."),
        sentence("V", "y", "dra si hrála u potoka."),
      ],
      mediumSentences: [
        sentence("V", "y", " jste splnili úkol lépe, než jsme čekali."),
        sentence("Na skalní římse seděl mohutný v", "ý", "r a sledoval okolí."),
        sentence("Ve tmě lesem zněl táhlý vlčí v", "ý", "t, který nás trochu vyděsil."),
        sentence("Záchranáři spatřili v", "y", "dru, která si hrála u potoka."),
        sentence("V", "ý", "soké hory přitahují každý rok tisíce horolezců."),
        sentence("Diváci v", "ý", "skali a tleskali, když hráč vstřelil vítězný gól."),
        sentence("V", "y", "žle je štíhlý lovecký pes, který pochází z Maďarska."),
        sentence("Tatínek v", "y", "právoval o svém dětství na vesnici."),
        sentence("Maminka v", "y", "světlila, jak se správně myje nádobí."),
        sentence("V", "ý", "soká budova se tyčila nad celým náměstím."),
        sentence("Učitelka v", "y", "brala obrázky, které pak visely na chodbě."),
        sentence("V", "y", "dra je chráněný živočich, který žije u čistých řek."),
        sentence("Záchranáři v", "y", "tahali uvízlé auto ze zatopeného příkopu."),
        sentence("V", "ý", "r je největší noční sova, která žije v Evropě."),
        sentence("Děti radostně v", "ý", "skaly, když se dovědely o výletu."),
        sentence("V", "y", "prali jsme prádlo a pověsili ho na šňůru."),
      ],
      trickQuestions: [
        sentence("Z okna jsme v", "i", "děli celé město."),
        sentence("Venku foukal silný v", "í", "tr."),
        sentence("V", "í", "m, že to dokážeš."),
        sentence("Na louce kvetla krásná v", "i", "olka."),
        sentence("Závodník byl v", "í", "těz celého závodu."),
        sentence("Maminka přátelsky v", "í", "tala hosty u dveří."),
        sentence("V pohádce létala bílá v", "í", "la nad jezerem."),
        sentence("V řece byl silný v", "í", "r, proto jsme neplavali."),
        sentence("Lékař řekl, že ho skolil nebezpečný v", "i", "rus."),
        sentence("V", "i", "nice se zelenala na slunečném svahu."),
        sentence("Dítě v", "i", "dělo za oknem sněhové vločky."),
        sentence("Svědek u soudu musel říct, co v", "i", "děl."),
        sentence("Závodník jako v", "í", "těz dostal zlatou medaili."),
        sentence("V pohádce se o princeznu starala hodná v", "í", "la."),
        sentence("Za oknem byl silný v", "í", "tr a pršelo."),
        sentence("Na zahradě v", "i", "děli lišku, jak se krade ke kurníku."),
      ],
    },
  },
  Z: {
    targetTotal: 80,
    categories: {
      basicWords: [
        sentence("Vstávání brzy ráno je dobrý zv", "y", "k."),
        sentence("Jak se naz", "ý", "vá tahle ulice?"),
        sentence("Přijď brz", "y", ", ať nestihneme oběd."),
        sentence("Na češtině probíráme jaz", "y", "k a pravopis."),
        sentence("Zv", "y", "k zdravého stravování mu prospívá."),
        sentence("Hora se naz", "ý", "vá Sněžka."),
        sentence("Tato ryba se jaz", "ý", "čkem chytá mouchy."),
        sentence("Brz", "y", " nastane jaro a rozkvetou stromy."),
        sentence("Každý jaz", "y", "k má svá pravidla a slovník."),
        sentence("Naz", "ý", "váme ji přezdívkou Slunečnice."),
        sentence("Jaz", "ý", "ček zvonu se rozhoupal a zazvonil."),
        sentence("Stará tradice je dávný zv", "y", "k předků."),
        sentence("Brz", "y", " se uvidíme zase na hřišti."),
        sentence("Jaz", "y", "k je sval v ústech, který pomáhá mluvit."),
        sentence("Tento kraj se naz", "ý", "vá Vysočina."),
        sentence("Zv", "y", "k zdravého spánku je velmi důležitý."),
      ],
      relatedWords: [
        sentence("Zv", "y", "kl si vstávat v šest hodin každý den."),
        sentence("Jak se naz", "ý", "vá tato hora? Nikdo nevěděl."),
        sentence("Český jaz", "y", "k má mnoho výjimek z pravidel."),
        sentence("Brz", "y", " přijde zima a napadne sníh."),
        sentence("Zv", "y", "kově přichází tatínek domů v pět."),
        sentence("Tato vesnice se naz", "ý", "vá Lhota pod Strání."),
        sentence("Naučit se cizí jaz", "y", "k trvá mnoho let."),
        sentence("Brz", "y", " to bude lépe, řekla maminka."),
        sentence("V muzeu vystavují starý jaz", "ý", "ček z věže kostela."),
        sentence("Jak se naz", "ý", "vá tenhle pták? Je to dudek."),
        sentence("Zv", "y", "k ranního cvičení mu pomáhá být fit."),
        sentence("Jaz", "y", "k a literatura jsou moje oblíbené předměty."),
        sentence("Brz", "y", " nastane čas, kdy to budeme umět."),
        sentence("Jaz", "ý", "ček u boty se odtrhl a museli jsme ho přišít."),
        sentence("Naz", "ý", "váme ten les Zakletý, protože tam prý straší."),
        sentence("Zv", "y", "k říkat dobré ráno je zdvořilý."),
      ],
      easySentences: [
        sentence("Ranní vstávání je dobrý zv", "y", "k."),
        sentence("Jak se naz", "ý", "vá ta řeka?"),
        sentence("Brz", "y", " půjdeme domů."),
        sentence("Učím se anglický jaz", "y", "k."),
        sentence("Ten zv", "y", "k je starý."),
        sentence("Hora se naz", "ý", "vá Říp."),
        sentence("Zvon má velký jaz", "ý", "ček."),
        sentence("Přijď brz", "y", "!"),
        sentence("Jaz", "y", "k je v ústech."),
        sentence("Zv", "y", "k mytí rukou je zdravý."),
        sentence("Jak se naz", "ý", "vá ta ulice?"),
        sentence("Brz", "y", " bude zima."),
        sentence("Češtiny je krásný jaz", "y", "k."),
        sentence("Ten zvon má velký jaz", "ý", "ček."),
        sentence("Zv", "y", "kně chodíme spát v devět."),
        sentence("Naz", "ý", "vají ho Honza."),
      ],
      mediumSentences: [
        sentence("Dobrý zv", "y", "k pravidelného čtení pomáhá při učení."),
        sentence("Jak se naz", "ý", "vá nejvyšší hora v Čechách? Je to Sněžka."),
        sentence("Na škole probíráme český jaz", "y", "k a jeho pravidla."),
        sentence("Brz", "y", " nastane jaro a přijdou první teplé dny."),
        sentence("Zv", "y", "kl si každé ráno dělat krátké cvičení."),
        sentence("Tato vesnice se naz", "ý", "vá Dolní Třešňovec."),
        sentence("Jaz", "y", "k je nejpohyblivější sval v lidském těle."),
        sentence("Brz", "y", " se uvidíme, slíbil kamarád před odjezdem."),
        sentence("Zvon na věži má velký těžký jaz", "ý", "ček z kovu."),
        sentence("Jak se naz", "ý", "vá ten ptáček se červeným bříškem? Červenka."),
        sentence("Zv", "y", "k zdravého spánku je pro děti velmi důležitý."),
        sentence("Cizí jaz", "y", "k se učíme proto, abychom si rozuměli s lidmi z celého světa."),
        sentence("Brz", "y", " přijde čas, kdy se vše zlepší, věřila babička."),
        sentence("Jaz", "ý", "ček u boty se odtrhl, a tak jsme museli zajít k ševci."),
        sentence("Naz", "ý", "váme ji přezdívkou Kočička, protože miluje kočky."),
        sentence("Zv", "y", "k říkat děkuji a prosím je základem slušného chování."),
      ],
      trickQuestions: [
        sentence("Z", "í", "tra půjdeme na výlet do lesa."),
        sentence("V lednu bývá velká z", "i", "ma."),
        sentence("Z", "i", "mní kabát jsem si vzal na procházku."),
        sentence("Všichni z", "í", "rali na nový autobus."),
        sentence("Z", "í", "tra ráno máme test z matematiky."),
        sentence("Z", "i", "sk z prodeje byl vyšší než loni."),
        sentence("Z", "í", "val celou hodinu, protože šel pozdě spát."),
        sentence("Na podzim se z", "i", "my nebojíme, máme teplé oblečení."),
        sentence("Z", "í", "tra se probudím brzy a přijdu včas."),
        sentence("Z", "i", "mní sporty jsou lyžování a bruslení."),
        sentence("Chlapci z", "í", "rali na výlohu obchodu."),
        sentence("Z", "i", "sku z podnikání mu záviděli."),
        sentence("Z", "í", "val únavou, protože šel pozdě spát."),
        sentence("Z", "i", "ma mi vadí víc než vedro."),
        sentence("Z", "í", "tra bude hezky, říká předpověď počasí."),
        sentence("V z", "i", "mě chodíme na kluzišti bruslit."),
      ],
    },
  },
};

export const CATEGORY_ORDER = [
  "basicWords",
  "relatedWords",
  "easySentences",
  "mediumSentences",
  "trickQuestions",
];

export const CATEGORY_META = {
  basicWords: { label: "Základní vyjmenovaná slova", target: TARGET_PER_CATEGORY },
  relatedWords: { label: "Příbuzná slova", target: TARGET_PER_CATEGORY },
  easySentences: { label: "Lehké věty", target: TARGET_PER_CATEGORY },
  mediumSentences: { label: "Střední věty", target: TARGET_PER_CATEGORY },
  trickQuestions: { label: "Chytáky", target: TARGET_PER_CATEGORY },
};

export function getSentencePool(letter) {
  const entry = SENTENCE_BANK[letter];
  if (!entry) return [];

  return CATEGORY_ORDER.flatMap((category) => entry.categories[category] || []);
}

export function getSentencePoolByCategories(letter, categories) {
  const entry = SENTENCE_BANK[letter];
  if (!entry) return [];
  const cats = categories && categories.length > 0 ? categories : CATEGORY_ORDER;
  return cats.flatMap((cat) => entry.categories[cat] || []);
}

export function getBankSummary(letter) {
  const entry = SENTENCE_BANK[letter];
  if (!entry) return null;

  const counts = Object.fromEntries(
    CATEGORY_ORDER.map((category) => [category, (entry.categories[category] || []).length]),
  );

  const total = Object.values(counts).reduce((sum, count) => sum + count, 0);

  return {
    letter,
    targetTotal: entry.targetTotal,
    total,
    counts,
  };
}
